/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dosen;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import projectsiakad.*;
import entitas.*;
import implement.*;

/**
 *
 * @author ASUS
 */
public class DataNilai extends javax.swing.JFrame {

    List<Nilai> record = new ArrayList<Nilai>();
    NilaiImplement nilai_im;
    int row;
    /**
     * Creates new form DataNilai
     */
    public DataNilai() {
        try {
            initComponents();
            nilai_im = new NilaiImplement();
            setKdMatkul();
            lblNidn.setText(UserSession.getDosen().getNidn());
            lblNamaDosen.setText(UserSession.getDosen().getNama_dosen());
            tblNilai.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e){
                row = tblNilai.getSelectedRow();
                if (row!=-1) {
                    isiText();
                }
            }
        });
       this.statusAwal();
        } catch (SQLException ex) {
            Logger.getLogger(DataNilai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setKdMatkul() throws SQLException{
        NilaiImplement nilai = new NilaiImplement();
        combomatkul.addItem("-=Pilih=-");
        ArrayList<String> urutanArr = nilai.viewKdMatkul();
        for(Object o : urutanArr){
            combomatkul.addItem(o);
        }
    }
    
    private void setNpm(String kd_kelas) throws SQLException{
        NilaiImplement nilai = new NilaiImplement();
        comboNpm.addItem("-=Pilih=-");
        ArrayList<String> urutanArr = nilai.viewNpm(kd_kelas);
        for(Object o : urutanArr){
            comboNpm.addItem(o);
        }
    }
    
    void loadData(String kode_matkul){
        try{
            record = nilai_im.getAll(kode_matkul);
        } catch (SQLException ex){
            Logger.getLogger(DataNilai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void isiTabel(){
        Object data[][]= new Object[record.size()][6];
        int x=0;
        for(Nilai nilai:record){
            data[x][0]=nilai.getNpm();
            data[x][1]=nilai.getNama();
            data[x][2]=nilai.getNilai_tugas();
            data[x][3]=nilai.getNilai_uts();
            data[x][4]=nilai.getNilai_uas();
            data[x][5]=nilai.getIndex();
            x++;
        }
        String judul[]={"NPM", "Nama Mahasiswa", "Nilai Tugas", "Nilai UTS", "Nilai UAS", "Index"};
        tblNilai.setModel(new DefaultTableModel(data, judul));
        jScrollPane1.setViewportView(tblNilai);
    }
    
    void isiText(){
        Nilai nilai = record.get(row);
        //txtKelas.setText(nilai.getId_kelas());
        comboNpm.setSelectedItem(nilai.getNpm());
        lblNama.setText(nilai.getNama());       
        String nilai_tugas = String.valueOf(nilai.getNilai_tugas());
        txtTugas.setText(nilai_tugas);
        String nilai_uts = String.valueOf(nilai.getNilai_uts());
        txtUts.setText(nilai_uts);
        String nilai_uas = String.valueOf(nilai.getNilai_uas());
        txtUas.setText(nilai_uts);
        String nilai_akhir = String.valueOf(nilai.getNilai_akhir());
        lblNa.setText(nilai_akhir);
        txtIndex.setText(nilai.getIndex());
    }

    void kosongkanText(){
        combomatkul.setSelectedIndex(0);
        txtKelas.setText("");
        comboNpm.setSelectedIndex(0);
        lblNama.setText("");
        txtTugas.setText("");
        txtUts.setText("");
        txtUas.setText("");
        lblNa.setText("");
        txtIndex.setText("");
    }
    
    void statusAwal(){
        kosongkanText();
        String kode = (String) combomatkul.getSelectedItem().toString();
        String kodeFix = kode.substring(0, 7);
        loadData(kodeFix);
        isiTabel();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboNpm = new javax.swing.JComboBox();
        txtTugas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUts = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNilai = new javax.swing.JTable();
        combomatkul = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblNidn = new javax.swing.JLabel();
        lblNamaDosen = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNa = new javax.swing.JLabel();
        txtKelas = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        txtIndex = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnHitungNilai = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTambah1 = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        btnHapus1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NPM");

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama");

        comboNpm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboNpmItemStateChanged(evt);
            }
        });
        comboNpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNpmActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nilai Tugas");

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nilai UTS");

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nilai UAS");

        tblNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNilai);

        combomatkul.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        combomatkul.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combomatkulItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Matkul");

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kelas");

        lblNidn.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        lblNidn.setForeground(new java.awt.Color(255, 255, 255));
        lblNidn.setText("2110376528");

        lblNamaDosen.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        lblNamaDosen.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaDosen.setText("Yuyun Tresnawati M.Kom");

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nilai Akhir");

        lblNa.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        lblNa.setForeground(new java.awt.Color(255, 255, 255));
        lblNa.setText("100");

        txtKelas.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        txtKelas.setForeground(new java.awt.Color(255, 255, 255));
        txtKelas.setText("SI-A");

        lblNama.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setText("Ini Nama Buat Nama Mahasiswa");

        txtIndex.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        txtIndex.setForeground(new java.awt.Color(255, 255, 255));
        txtIndex.setText("A");

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Index");

        btnHitungNilai.setText("Hitung Nilai");
        btnHitungNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungNilaiActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Nilai Mahasiswa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(131, 131, 131)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22))))
        );

        btnTambah1.setFont(new java.awt.Font("Arial Narrow", 1, 15)); // NOI18N
        btnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah1ActionPerformed(evt);
            }
        });

        btnEdit1.setFont(new java.awt.Font("Arial Narrow", 1, 15)); // NOI18N
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        btnHapus1.setFont(new java.awt.Font("Arial Narrow", 1, 15)); // NOI18N
        btnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNidn, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(combomatkul, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblNama, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNa)
                                            .addComponent(comboNpm, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtUas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtUts, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(98, 98, 98)
                                        .addComponent(btnHitungNilai))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(112, 112, 112)
                                                .addComponent(txtIndex)))
                                        .addGap(53, 53, 53)
                                        .addComponent(btnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKelas)
                        .addGap(136, 136, 136))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNidn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNamaDosen)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combomatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtKelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboNpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtUts, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitungNilai))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblNa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtIndex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combomatkulItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combomatkulItemStateChanged
        try {
            // TODO add your handling code here:
            String kode="";
            if(combomatkul.getSelectedItem()!=null){
                kode = combomatkul.getSelectedItem().toString();
            }
            comboNpm.removeAllItems();
            String kodeFix = kode.substring(0, 7);
            txtKelas.setText(nilai_im.viewKdKelas(kodeFix).getKode_kelas());            
            setNpm(txtKelas.getText());
            loadData(kodeFix);
            isiTabel();
        } catch (SQLException ex) {
            Logger.getLogger(DataNilai.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_combomatkulItemStateChanged

    private void comboNpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNpmActionPerformed
        
    }//GEN-LAST:event_comboNpmActionPerformed

    private void comboNpmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboNpmItemStateChanged
        try {
            // TODO add your handling code here:
            String kode="";
            if(comboNpm.getSelectedItem()!=null){
                kode = comboNpm.getSelectedItem().toString();
            }
            lblNama.setText(nilai_im.viewNamaMahasiswa(kode).getNama_mhs());
        } catch (SQLException ex) {
            Logger.getLogger(DataNilai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboNpmItemStateChanged

    private void btnHitungNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungNilaiActionPerformed
        // TODO add your handling code here:
        int tugas = Integer.valueOf(txtTugas.getText());
        int uts = Integer.valueOf(txtUts.getText());
        int uas = Integer.valueOf(txtUas.getText());
        
        float na = (tugas+uts+uas)/3;
        
        if(na>=85){
            txtIndex.setText("A");
        } else if(na>=75){
            txtIndex.setText("B");
        } else if(na>=60){
            txtIndex.setText("C");
        } else if(na>=50){
            txtIndex.setText("D");
        } else{
            txtIndex.setText("E");
        }
        
        lblNa.setText(""+(int)na);
    }//GEN-LAST:event_btnHitungNilaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah1ActionPerformed
        try {
            // TODO add your handling code here:
            Nilai nilai = new Nilai();
            nilai.setNpm(comboNpm.getSelectedItem().toString());
            String kode = (String) combomatkul.getSelectedItem().toString();
            String kodeFix = kode.substring(0, 7);
            nilai.setId_matkul(kodeFix);
            int tugas = Integer.valueOf(txtTugas.getText());
            nilai.setNilai_tugas(tugas);
            int uts = Integer.valueOf(txtUts.getText());
            nilai.setNilai_uts(uts);
            int uas = Integer.valueOf(txtUas.getText());
            nilai.setNilai_uas(uas);
            int na = Integer.valueOf(lblNa.getText());
            nilai.setNilai_akhir(na);
            nilai.setIndex(txtIndex.getText());
            nilai_im.insert(nilai);
            this.statusAwal();
            JOptionPane.showMessageDialog(this, "data tersimpan!");
        } catch (SQLException ex) {
            Logger.getLogger(DataNilai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTambah1ActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Nilai nilai = new Nilai();
            nilai.setNpm(comboNpm.getSelectedItem().toString());
            String kode = (String) combomatkul.getSelectedItem().toString();
            String kodeFix = kode.substring(0, 7);
            nilai.setId_matkul(kodeFix);
            int tugas = Integer.valueOf(txtTugas.getText());
            nilai.setNilai_tugas(tugas);
            int uts = Integer.valueOf(txtUts.getText());
            nilai.setNilai_uts(uts);
            int uas = Integer.valueOf(txtUas.getText());
            nilai.setNilai_uas(uas);
            int na = Integer.valueOf(lblNa.getText());
            nilai.setNilai_akhir(na);
            nilai.setIndex(txtIndex.getText());
            nilai.setId_nilai(record.get(row).getId_nilai());
            nilai_im.update(nilai);
            this.statusAwal();
            JOptionPane.showMessageDialog(this, "data berhasil diubah!");
        } catch (SQLException ex) {
            Logger.getLogger(DataNilai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus1ActionPerformed
        try {
            // TODO add your handling code here:
            nilai_im.delete(record.get(row).getId_nilai()+"");
            this.statusAwal();
            JOptionPane.showMessageDialog(this, "data dihapus!");
        } catch (SQLException ex) {
            Logger.getLogger(DataNilai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHapus1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnHapus1;
    private javax.swing.JButton btnHitungNilai;
    private javax.swing.JButton btnTambah1;
    private javax.swing.JComboBox comboNpm;
    private javax.swing.JComboBox combomatkul;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNa;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNamaDosen;
    private javax.swing.JLabel lblNidn;
    private javax.swing.JTable tblNilai;
    private javax.swing.JLabel txtIndex;
    private javax.swing.JLabel txtKelas;
    private javax.swing.JTextField txtTugas;
    private javax.swing.JTextField txtUas;
    private javax.swing.JTextField txtUts;
    // End of variables declaration//GEN-END:variables
}
